### PR TITLE
Fix font change after running help

### PR DESCRIPTION
**Pull request by JMoVS**
Currently, when you run batch-transcode with --help, it currently never resets the display so the font color stays gray. I think this one-liner hopefully fixes this?

### CODE REVIEW

**Comment by JMoVS** [comment]
could you merge this?

**Comment by nwronski** [comment]
Which operating system and terminal program are you seeing this issue on? If you have a screenshot, could you post it here? The `display()` method is available on `charm`, so you'll need to change your fix to this to get it to run:

```javascript
charm.display('reset');
```

If you have cloned the repo locally, you can verify the fix resolves your issue by running the following in the root folder of the `batch-transcode-video` repo:

```
npm i
npm run build
node bin/batch-transcode-video --help
```

**Comment by JMoVS** [comment]
are you available on IRC/Freenode? #batch-transcode-video

**Comment by JMoVS** [comment]
this problem happens on MacOS, but apparently not on bash for windows...

**Comment by JMoVS** [comment]
Bildschirmfoto 2019-10-27 um 19 22 43

**Comment by JMoVS** [comment]
seems to be fixed as well according to the release notes

**Pull request closed without merging**
